title: Hexo
subtitle: "TODO:"
description: "TODO:"
author: Hexo
language: en
timezone: UTC

url: https://xyzwps.com
root: /
permalink: post/:year/:month/:day/:title/
archive_dir: post
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-135358050-1
fb_admins: 100000247608790  # TODO:
# algolia:                  # TODO:
#   en:
#     api_key: c3d5d4c995b5e0c2ffb5623900279a66
#     index_name: hexo
#   zh-cn:
#     api_key: cdea7d4e47d84f6145b77e7f68689f35
#     index_name: hexo_zh-cn
twitter: hexojs             # TODO:
github: hexojs/hexo         # TODO:

deploy:
  type: git
  repo: git@github.com:xyzwps/xyzwps.github.io.git
  branch: deploy