= 爬楼梯
weily <xyzwps@outlook.com>
v1.0, 2020-11-27
:toc:
:toc-title: 目录
:tag: 动态规划, DP, 斐波那契数列, LeetCode

## 问题

LeetCode 上的题目：link:https://leetcode-cn.com/problems/climbing-stairs/[70. 爬楼梯]。题目是说，给定一个
latexmath:[n] 阶的楼梯，我们要从底部爬到顶部，每次可以跨 1 阶或 2 阶楼梯，求有多少种爬法。

## 分析

这是一个动态规划问题，而且还很简单。设 `dp[i]` 表示爬到第 `i` 阶台阶的爬法数量。假设我们要爬到第 `i`
阶台阶，那么有两种做法：

. 从第 `i-1` 阶台阶往上跨1阶，共 `dp[i-1]` 种爬法
. 从第 `i-2` 阶台阶往上跨2阶，共 `dp[i-2]` 种爬法

于是 `dp[i] = dp[i-1] + dp[i-2]`。就这么简单。

请思考一下这个问题：从第 `i-2` 阶跨到第 `i` 阶台阶，应该有两种做法：一次往上跨2阶，和两次每次往上跨一阶。为什么这里只考虑了前一种情况？

## 代码

根据上面的分析，代码很容易就写出来了：

[source,js]
----
/**
 * @param {number} n
 * @return {number}
 */
const climbStairs = function (n) {
    const dp = [0, 1, 2];
    for (let i = 3; i <= n; i++) {
        dp[i] = dp[i-1] + dp[i-2];
    }
    return dp[n]
};
----

这里有两个优化点：

. 我们注意到在递推公式中，求第 `i` 项，只需要前两项，所以 `dp` 数组可以省略，只要保留最后两项就好了
. 我们注意到，对于输入 `i` 和 `j`（其中 `i < j`），`dp[t]`（对 latexmath:[\forall] `t ≤ i`），只需要计算一遍就好了。所以，可以把 `dp` 数组搞成全局变量，如果输入已经存在，就查表直接返回；否则就从 `dp` 的最后一个位置往后计算，直到算出结果，计算过程中，把中间结果保存下来待查。

## 斐波那契数列

我们注意到，递推公式 `dp[i] = dp[i-1] + dp[i-2]` 就是斐波那契数列的定义公式。这里和斐波那契数列的不同之处在于初值：

* 斐波那契数列：`a[1] = 1, a[2] = 1, a[3] = 2, a[4] = 3, a[5] = 5, a[6] = 8`
* 对 `dp` 数组：`dp[1] = 1, dp[2] = 2, dp[3] = 3, dp[4] = 5, dp[5] = 8`

所以，我们只要求出斐波那契数列的通项公式，或者直接对 `dp` 数组求通项公式，就可以根据输入直接算出结果了。
link:/post/math/sum/fibonacci.adoc[戳这里查看斐波那契数列通项公式算法]。

