= 最大子序和
weily <xyzwps@outlook.com>
v1.0, 2020-11-25
:toc:
:toc-title: 目录
:tag: 动态规划, DP, 数组, 最大子数组, 最大子序和, 分治, LeetCode

本来想刷一下 LeetCode 的动态规划题目，本来还想按顺序从简单题目开始，结果第一个题目就让我懵逼了——
link:https://leetcode-cn.com/problems/maximum-subarray/[第 53 题：最大子序和]。

## 最大子序和问题

题目是这样的：给定一个整数序列，找出所有连续子序列中和最大的那个，返回这个最大和。

为描述方便，我们约定一下说法和符号：

* 我们设输入序列为 latexmath:[a]，索引从 latexmath:[0] 开始，长度为 latexmath:[n]（即最后一个元素的索引为 latexmath:[n-1]）
* latexmath:[a] 中连续子序列中和最大的序列，称为**最大子序列**。显然最大子序列可能不止一个。
* 我们要设计的目标函数记为 latexmath:[\textrm{maxSubArray}(a)]，它输出 latexmath:[a] 中最大子序列的和。
* 对于序列 latexmath:[a]，
** latexmath:[a[i,j\]] 表示从 latexmath:[i] 到 latexmath:[j] 且包含 latexmath:[a[j\]] 的子序列
** latexmath:[a[i,j)] 表示从 latexmath:[i] 到 latexmath:[j] 但不包含 latexmath:[a[j\]] 的子序列

这既然是个 DP 题目，那就想想 DP 的解法呗，毕竟是简单题目。最终，没想出来。还是从暴力解法开始找思路吧。

## 暴力解法

简单来说，就是对 latexmath:[a] 的每个子序列求和，然后比较得出最大的和即可。这个算法可以做到 latexmath:[O(n^2)]。

因为想法是如此的简单，所以代码就略过吧。

## Kadane 算法

这个算法是从头开始累加，把累加结果的最大值记下来。如果累加结果出现负数，直接丢掉（因为最大子序列不可能有一个和为负数的前缀），
从丢掉的位置下一个地方开始重新累加。沿着这个思路，可以写出下面的代码：

[source,js]
----
/**
 * @param {number[]} nums
 * @return {number}
 */
function maxSubArray (nums) {
    let max = maxSoFar = nums[0];
    for (let i = 1; i < nums.length; i++) {
        const num = nums[i];
        if (maxSoFar < 0) {
            maxSoFar = 0;
        }
        maxSoFar += num;
        max = Math.max(maxSoFar, max);
    }
    return max;
};
----

## DP 算法

DP 算法首先要考虑的问题是 DP 什么，但这并不好想。

我们考察 latexmath:[a] 的所有形如 latexmath:[a[0,i\]] 的子列。对于每一个 latexmath:[a[0,i\]]，我们把它从第 latexmath:[i]
个位置往前累加，累加过程中得到的最大和记为 latexmath:[s[i\]]（这样 latexmath:[s] 就是一个长度为
latexmath:[n] 的数组）。于是 latexmath:[\textrm{maxSubArray}(a)] 的值就是 latexmath:[s] 中的最大值。
这基本上算是暴力解法的一个翻版了。举个例子，设 latexmath:[a = [-2, 1, -3, 4\]]，那么 latexmath:[s = [-2, 1, -2, 4\]]，于是
latexmath:[\textrm{maxSubArray}(a)] 就是数组 latexmath:[s] 中的最大值，也就是 4。

这个解法毕竟是 DP 算法，不是暴力算法。原因是，我们可以求出从 latexmath:[s[i-1\]] 到 latexmath:[s[i\]] 的递推公式。我们要把
latexmath:[a[i\]] 补到 latexmath:[a[0,i-1\]] 后面以求出 latexmath:[s[i\]]。
假设 latexmath:[s[i-1\] \gt 0]，那么自然 latexmath:[s[i\] = s[i-1\] + a[i\]]；否则，latexmath:[s[i\] = a[i\]]。
这一点也一定要想明白。

现在我们知道了，要 DP 的是 latexmath:[s]。下面的代码就是对上面思路的一个翻译：

[source,js]
----
/**
 * @param {number[]} a
 * @return {number}
 */
function maxSubArray (a) {
    const s = [a[0]];
    for (let i = 1; i < a.length; i++) {
        if (s[i-1] > 0) {
            s[i] = s[i-1] + a[i];
        } else {
            s[i] = a[i];
        }
    }

    let result = s[0];
    for (const n of s) {
        result = Math.max(n, result);
    }
    return result;
};
----

这段代码可以优化。首先，`if (s[i-1] > 0)` 这段代码很啰嗦，于是代码可以改成这样：

[source,js]
----
/**
 * @param {number[]} a
 * @return {number}
 */
function maxSubArray (a) {
    const s = [a[0]];
    for (let i = 1; i < a.length; i++) {
        s[i] = Math.max(s[i-1] + a[i], a[i]);
    }

    let result = s[0];
    for (const n of s) {
        result = Math.max(n, result);
    }
    return result;
};
----

因为我们关心的其实是 latexmath:[s] 数组的最大值，我们在求 latexmath:[s] 数组时，就可以把它的最大值求出来了，
所以不用专门申请一块内存来存放 latexmath:[s]。于是，我们把求 latexmath:[s] 最大值的逻辑放到第一个 `for`
循环里进行，这样既省了 latexmath:[s] 数组的空间，又省掉了下面的 `for` 循环。最后变成了这样：

[source,js]
----
/**
 * @param {number[]} a
 * @return {number}
 */
function maxSubArray (a) {
    let result = scurr = nums[0];
    for (let i = 1; i < a.length; i++) {
        scurr  = Math.max(scurr + a[i], a[i]);
        result = Math.max(scurr, result);
    }
    return result;
};
----

也就是很多地方给出的 dp 版代码了。

## 分治法

LeetCode 的题解中还给了一个“精妙”的分治算法。这里把它捋一遍。

这里的分治算法，实际上是二分法。它把数组从中间切成两段，对每一段算出一些信息，然后根据这些信息，聚合出原数组的最大子序和。对于数组
latexmath:[a] 的一个子列 latexmath:[a[i,j\]]，我们要计算出这些信息：

* `lsum`：从 latexmath:[a[i\]] 顺序累加到 latexmath:[a[j\]] 的过程中的那个最大和；
* `rsum`：从 latexmath:[a[j\]] 逆序累加到 latexmath:[a[i\]] 的过程中的那个最大和；
* `tsum`：latexmath:[a[i,j\]] 中每一项的和；
* `msum`：latexmath:[a[i,j\]] 的最大子序和。

我们定义类：

[source,js]
----
class SubArrayInfo {
    constructor(i, j, lsum, rsum, tsum, msum) {
        this.i = i;
        this.j = j;
        this.lsum = lsum;
        this.rsum = rsum;
        this.tsum = tsum;
        this.msum = msum;
    }
};
----

假设 latexmath:[a[i,j\]] 被二分为两个部分：latexmath:[a[i, m\]] 和 latexmath:[a[m+1,j\]]，下面我们考虑如何从
`SubArrayInfo(i, m, ...)` 和 `SubArrayInfo(m+1, j, ...)` 中还原出 `SubArrayInfo(i, j, ...)`。为方便，这里记

[source]
----
target = SubArrayInfo(i, j, ...)
left   = SubArrayInfo(i, m, ...)
right  = SubArrayInfo(m + 1 , j, ...)
----

要从 `left` 和 `right` 还原出 `target` 的话，有下面的公式：

[source]
----
target.lsum = max(left.lsum, left.tsum + right.lsum)   # <1>
target.rsum = max(right.rsum, right.tsum + left.rsum)  # <2>
target.tsum = left.tsum + right.tsum)  # <3>
target.msum = max(left.msum, right.msum, left.rsum + right.lsum) # <4>
----

<1> `target.lsum` 要么在左边，要么跨左边和右边。如果在左边，就是 `left.lsum`；如果在右边，就是 `left.tsum + right.lsum`。证明很简单，略。这样 `target.lsum` 取两者的最大值就可以了。
<2> `target.rsum` 的计算思路和 `target.lsum` 相同。
<3> 按定义是显然的
<4> `target.msum` 要么在左边，要么在右边，要么跨两边。如果在左边，就只能是 `left.msum`；如果在右边，就只能是 `right.msum`；如果跨两边，
就只能是 `left.rsum + right.lsum`。证明方法和 <1> 类似，忽略。现在 `target.msum` 只要取三者的最大值就好了。

至此，准备工作完毕，把上面的分子整理成代码，如下：

[source,js]
----
/**
 * @param {number[]} a
 * @return {number}
 */
var maxSubArray = function (a) {
    function divideAndConquer(i, j) {
        if (i === j) {
            return new SubArrayInfo(i, j, a[i], a[i], a[i], a[i]);
        }
        const m =  Math.floor((j + i) / 2);
        const left = dac(i, m);
        const right = dac(m + 1, j);

        const lsum = Math.max(left.lsum, left.tsum + right.lsum);
        const rsum = Math.max(right.rsum, right.tsum + left.rsum);
        const tsum = left.tsum + right.tsum;
        const msum = Math.max(left.msum, right.msum, left.rsum + right.lsum);

        return new SubArrayInfo(i, j, lsum, rsum, tsum, msum);
    }

    return divideAndConquer(0, a.length - 1).msum;
};
----

观察代码发现，`SubArrayInfo` 类的 `i` 和 `j` 其实是没有被使用到的，所以代码可以改成这样：

[source,js]
----
class SubArrayInfo {
    constructor(lsum, rsum, tsum, msum) {
        this.lsum = lsum;
        this.rsum = rsum;
        this.tsum = tsum;
        this.msum = msum;
    }
};

/**
 * @param {number[]} a
 * @return {number}
 */
var maxSubArray = function (a) {

    function divideAndConquer(i, j) {
        if (i === j) {
            return new SubArrayInfo(a[i], a[i], a[i], a[i]);
        }
        const m =  Math.floor((j + i) / 2);
        const left = dac(i, m);
        const right = dac(m + 1, j);

        const lsum = Math.max(left.lsum, left.tsum + right.lsum);
        const rsum = Math.max(right.rsum, right.tsum + left.rsum);
        const tsum = left.tsum + right.tsum;
        const msum = Math.max(left.msum, right.msum, left.rsum + right.lsum);

        return new SubArrayInfo(lsum, rsum, tsum, msum);
    }

    return divideAndConquer(0, a.length - 1).msum;
};
----



## 参考

* link:https://leetcode-cn.com/problems/maximum-subarray/[LeetCode：最大子序和]。
* link:https://en.wikipedia.org/wiki/Maximum_subarray_problem[Baeldung：Maximum Subarray Problem in Java]
* link:https://zh.wikipedia.org/wiki/%E6%9C%80%E5%A4%A7%E5%AD%90%E6%95%B0%E5%88%97%E9%97%AE%E9%A2%98[维基百科：最大子数列问题]
* link:https://cloud.tencent.com/developer/article/1403056[腾讯云社区：53. Maximum Subarray （Kadane算法 / 动态规划 / 分治法）]
