= 分割回文串 II
weily <xyzwps@outlook.com>
v1.0, 2020-12-21
:toc:
:toc-title: 目录
:tag: 动态规划, DP, 数组, 回文, LeetCode

题目link:https://leetcode-cn.com/problems/palindrome-partitioning-ii/[132. 分割回文串 II]。
刚开始的时候，花了非常长的时间去调试暴露解法，结果暴力解法超时。之后冷静想一想，想到一个 DP 方案，跑了一下效率还可以，这里记录下。

这一题是求把一个字符串分割成一些子串，使得这些子串都是回文串的最小分割数。设把一个字符串分割成一些子串，
使得这些子串都是回文串的最少子串个数，那么答案就是最小子串个数减一。举个例子：设 `s = "abaabac"`，可以把它分成这样：
`"aba", "aba", "c"`，也可以分成 `"abaaba", "c"`，甚至还有别的分割方法。肉眼观察，显现 `"abaaba", "c"`
是分割后可以得到最少子串的方案，所以最少可以分割成 2 个回文子串，只需要分割 1 次。

为讨论方便，设输入数组为 latexmath:[s]：其从第 latexmath:[a] 个字符到第 latexmath:[b] 个字符构成的子串为
latexmath:[s[a,b\]]；如果子串不包含第 latexmath:[b] 个字符，则记为 latexmath:[s[a,b)]；
其第 latexmath:[a] 个字符记为 latexmath:[s[a\]]。

记 latexmath:[dp[i\]]（提前暴露）表示子串 latexmath:[s[0,i\]] 被分割为一些回文子串时，得到的最少子串数。
我们的目的是从 latexmath:[dp[0\]] 到 latexmath:[dp[i-1\]] 出发，得到 latexmath:[dp[i\]]。首先 latexmath:[dp[0\]] 肯定是 1。

对于字符串 latexmath:[s[0,i\]]，会被分割成几个回文子串，比如分割成这样 latexmath:[s[0,t_1), s[t_1,t_2), ..., s[t_k,i\]]。
这一些列子串可以看成两部分 latexmath:[s[0,t)] 和 latexmath:[s[t,i\]]（这里取 latexmath:[t = t_k]），
其中 latexmath:[s[t,i\]] 是一个回文子串，latexmath:[dp[t-1\]] 已知。那么 latexmath:[dp[i\]] 是否就是 latexmath:[dp[t-1\] + 1]
呢？不一定，因为在 latexmath:[s[0,i\]] 中，以 latexmath:[s[i\]] 结尾的回文子串可不止一个。这样的话，
latexmath:[dp[i\]] 就应该来自可以使得 latexmath:[dp[t-1\]] 最小的那个 latexmath:[s[t,i\]]。

设 latexmath:[s[0,i\]] 中，所有以 latexmath:[s[i\]] 结尾的回文串构成的集合为
latexmath:[\{ s[t_1,i\], s[t_2,i\], ..., s[t_k,i\] \}]。由以上的分析可以知道，
latexmath:[dp[i\] = \min \limits_{1 \le a \le k} \{ dp[t_a-1\] + 1 \}]。另外，我们注意到，当
latexmath:[s[0,i\]] 本身就是回文串的时候，是没办法套用这个公式的，但是因为它本身就是回文串，所以 latexmath:[dp[i\] = 1]。
这样状态转义方程就被我们推出来了。

下面的问题就是，我们要对 latexmath:[s] 找出所有的以 latexmath:[s[i\]]
结尾的回文串。这个就比较简单了，不管是暴力法，还是中心扩散法（也算是暴力法），代码都很容易写，总之要把所有的回文串都找出来。
这样，问题在逻辑上就算被解决了。下面贴一下我自己的代码，风格不怎么好，就先这样吧：

[source,js]
----

/**
 * @param {string} s
 * @return {number}
 */
var minCut = function(s) {
  const endMap = {} // 存储所有以 s[i] 结尾的回文子串的长度
  for(let i = 0; i < s.length; i++) {
    expandEven(i)
    expandOdd(i)
    addToEndMap(i, 1)
  }

  const dp = [1]
  for(let i = 1; i < s.length; i++) {
      dp[i] = s.length
    for(let len of endMap[i]) {
      if (len > i){
        dp[i] = 1
        break
      } else {
        dp[i] = Math.min(dp[i], dp[i - len] + 1)
      }
    }
  }

  return dp[s.length - 1] - 1

  function addToEndMap(end, len) {
    if (!(end in endMap)) endMap[end] = []
    endMap[end].push(len)
  }

  // 中心扩散法找所有长度为偶数的回文串
  function expandEven(p) {
    let result = 0;
    for(let i = p + 1; i < s.length && 2*p+1-i >= 0; i++) {
        if (s[i] == s[2*p+1-i]) {
            result+=2
            addToEndMap(i, result)
        } else {
          break
        }
    }
  }

  // 中心扩散法找所有长度为奇数的回文串
  function expandOdd(p) {
    let result = 1;
    for(let i = p + 1; i < s.length && 2*p-i >= 0; i++) {
        if (s[i] == s[2*p-i]) {
            result+=2
            addToEndMap(i, result)
        } else {
          break
        }
    }
  }
};
----